//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
   
    public partial class Entradas_Salidas
    {
        public int idEntradas_Salidas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idGestion { get; set; }
        public Nullable<int> idZapato { get; set; }
        public Nullable<int> cantidadProducto { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idUbicacion { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public string descripcion { get; set; }
    
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Zapato> Zapato { get; set; }
        public virtual ICollection<Proveedor >Proveedor { get; set; }
        public virtual ICollection<TipoGestion> TipoGestion { get; set; }
    }
}
