//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entradas_Salidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entradas_Salidas()
        {
            this.DetalleEntradas_Salidas = new HashSet<DetalleEntradas_Salidas>();
        }
    
        public int idEntradas_Salidas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idGestion { get; set; }
        public Nullable<int> cantidadTotal { get; set; }
        public int idUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEntradas_Salidas> DetalleEntradas_Salidas { get; set; }
        public virtual TipoGestion TipoGestion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
