//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int idUbicacion { get; set; }
        public int idZapato { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Zapato Zapato { get; set; }
    }
}
